const INIT_CITY = 'INIT_CITY'
const CHANGE_CITY = 'CHANGE_CITY'
const UPDATE_SEARCH = 'UPDATE_SEARCH'
const _LOGIN = '_LOGIN'
const _LOGOUT = '_LOGOUT'
const SUBSCRIBE = 'SUBSCRIBE'
const UN_SUBSCRIBE = 'UN_SUBSCRIBE'

export {
  INIT_CITY,
  CHANGE_CITY,
  UPDATE_SEARCH,
  _LOGIN,
  _LOGOUT,
  SUBSCRIBE,
  UN_SUBSCRIBE
}